add a gui; initial dev release

diff --git a/publish-repo b/publish-repo
--- a/publish-repo
+++ b/publish-repo
@@ -3,10 +3,17 @@
 set -o pipefail
 
 . config
+. sh-lib
 
-version="$(find "$roots" -mindepth 1 -maxdepth 1 -type d | cut -d/ -f2 | sort -rn | head -1)"
+# Check for dependencies:
+package_deps ostree
 
-[ ! -d "$repo" ] && ostree --repo="$repo" init --mode=archive
+version="$(cd "${roots:?}"/"${branch:?}"; find ./ -mindepth 1 -maxdepth 1 -type d | cut -d/ -f2 | sort -rn | head -1)"
+
+if [ ! -d "$repo" ]; then
+	mkdir -p "$repo"
+	ostree --repo="$repo" init --mode=archive
+fi
 
 REF=$(ostree --repo="$build_repo" rev-parse "$branch")
 
@@ -15,9 +22,9 @@ ostree --repo="$repo" pull-local "$build_repo" "$REF"
 ostree --repo="$repo" commit -b "$branch" \
 	-s "$osname/$osversion:($osdesc) $branch $version" \
 	--add-metadata-string=version="$branch":"$version" \
-	--gpg-sign=CE4A0BF21E1C237DD8C400FAA39487B22697143F \
+	--gpg-sign=91BC029A6B3701253B585656C5FE25B2138B1F0F \
 	--tree=ref="$REF"
 
-ostree --repo="$repo" static-delta generate "$branch" || echo "Warning: static-delta generate failed" >&2
+ostree --repo="$repo" static-delta generate "$branch" || echo "Warning: static-delta generate failed, (they grow up so fast...)" >&2
 
 ostree --repo="$repo" summary -u
